### ISSUE TITLE
写错了4.1

### ISSUE THREAD

**Issue by BreakingLead** [FledgeXu/Boson#4]
这就是注册的全部内容，首先我们创建了一个类型为DeferredRegister<Item>名字叫做ITEMS的变量，这个泛型表明我们需要注册的东西是物品，然后通过new DeferredRegister<>(ForgeRegistries.ITEMS, Utils.MOD_ID);实例化了这个类，这个类里有两个参数ForgeRegistries.ITEMS代表了我们要注册的是物品，第二个参数填入的应该是你的modId。这样我们就创建好了注册器，接下去就是注册我们的物品。

这一段不相符。没有实例化DeferredRegister这个类，只是用了create方法（新版）

**Comment by FledgeXu** [comment]
请发PR
