### ISSUE TITLE
导论链接失效

### ISSUE THREAD

**Issue by TaoismDeepLake** [FledgeXu/Boson#7]
那么如果你现在还不会编程怎么办？没关系，这里有个教程推荐给你：Minecraft mod 开发编程入门

**Comment by TaoismDeepLake** [comment]
Minecraft mod 开发编程入门指向的链接404 File not found

**Comment by FledgeXu** [comment]
因为论坛已经Archive了，所以就失效了。
对应的地址应该是这个：https://v2mcdev.com/posts/88.html
