### ISSUE TITLE
4.1 接口更新

### ISSUE THREAD

**Issue by TaoismDeepLake** [FledgeXu/Boson#8]
`super(new Properties().group(ItemGroup.MATERIALS));`
在1.16.5-36.1.0中，group成员被改名为tab。现在的写法是：
`super(new Properties().tab(ItemGroup.TAB_MATERIALS));`
建议备注上

**Comment by FledgeXu** [comment]
我现在对Minecraft Mod开发没什么兴趣，如果你觉得需要修改，请发PR。
